apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: todo-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - image: localhost:5001/todo-app
        name: todo-app
        ports:
        - containerPort: 8000
          name: todo-app
