apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: todo-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - image: localhost:5001/todo-app
        name: todo-app
        env:
          - name: DATABASE_DRIVER
            value: postgresql
          - name: DATABASE_HOST
            value: postgres
          - name: DATABASE_NAME
            value: postgres
          - name: SECRETS_CONFIG_FILEPATH
            value: /run/secrets/postgres
        ports:
        - containerPort: 8000
          name: todo-app
        volumeMounts:
        - name: secret-volume
          mountPath: /run/secrets/postgres
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: dbcredentials
