apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:16.3-alpine3.20
        name: postgres
        env:
        - name: POSTGRES_USER_FILE
          value: /run/secrets/postgres/username
        - name: POSTGRES_PASSWORD_FILE
          value: /run/secrets/postgres/password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
        - name: secret-volume
          mountPath: /run/secrets/postgres
          readOnly: true
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-kind
      - name: secret-volume
        secret:
          secretName: dbcredentials