apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kind
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /kind_volume
  persistentVolumeReclaimPolicy: Retain
